debug: true
---
app:
  version: @project.version@
---
server:
  port: 8089
spring:
  banner:
    # Custom Banner
    location: classpath:banner.txt
---
# Health check actuator
management:
  endpoints:
    jmx:
      exposure:
        include: "*"
    web:
      exposure:
        include: "*"
---
# Custom settings
nft-bot:
  custom:
    - baseUrl: "https://pixelfellazgif.s3.us-east-1.amazonaws.com/left_static/"
      command: "pixel"
      fileFormat: ".png"
      max: 10000
    - baseUrl: "https://pixelfellazgif.s3.us-east-1.amazonaws.com/front_gif/"
      command: "pixelgif"
      fileFormat: ".gif"
      max: 10000
    - baseUrl: "https://%ipfs%/ipfs/bafybeidkqhbiyjlnnneab467eh2mabdf7lcdhmv6wgnd6peaq7hmfj3ez4/"
      command: "fff"
      fileFormat: ".png"
      max: 10000
    - baseUrl: "https://%ipfs%/ipfs/bafybeiep5n2kci72it4kny7rcvxryotlnp75ucz6wj4vkxu7orzkuqgbvu/"
      command: "fff"
      fileFormat: ".png"
      max: 10000
    - baseUrl: "https://%ipfs%/ipfs/bafybeih546bp5uwvco2zknvbpkmwds5l2q36yl6yq5vbdjjxdl55n6bvbq/"
      command: "fff"
      fileFormat: ".png"
      max: 10000
  discord:
    prefix: "!"
    token: ODg1MzE2NjE1MjEyNzY5Mjgx.YTlRWQ.Wz4efIUN3RX-_D1RlczaDJDIJQk
    channelId: "1088876843291119769"